// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrrGtlbGKHL9R2s1ZFsoE0NtoBRXrQyFw',
    appId: '1:64395988047:web:5b0205f94e988b5b686e3a',
    messagingSenderId: '64395988047',
    projectId: 'gulf-coast-comma',
    authDomain: 'gulf-coast-comma.firebaseapp.com',
    storageBucket: 'gulf-coast-comma.appspot.com',
    measurementId: 'G-SF778S20H6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsPG5sfsPzR2n0kAMzwMGzQcejmCgyV3M',
    appId: '1:64395988047:android:d1bcfa1781299b4c686e3a',
    messagingSenderId: '64395988047',
    projectId: 'gulf-coast-comma',
    storageBucket: 'gulf-coast-comma.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiyhMcwvJSWMjeV4u0VY7bq88kE7xouGE',
    appId: '1:64395988047:ios:70913a412852e6a8686e3a',
    messagingSenderId: '64395988047',
    projectId: 'gulf-coast-comma',
    storageBucket: 'gulf-coast-comma.appspot.com',
    iosBundleId: 'com.comma.gulfcoast',
  );
}
